# Generated by Django 5.1.4 on 2025-01-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='place',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
