# Generated by Django 5.1.4 on 2025-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_register_phone_alter_register_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='availability',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
