# Generated by Django 5.1.4 on 2025-01-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0001_initial'),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destination.destination'),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
