# Generated by Django 5.1.4 on 2025-01-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
        ('agency_app', '0003_activity_travel_id'),
        ('feedback', '0003_feedback_accommodation_feedback_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_feedbacks', to='accomodation.accommodation'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_feedbacks', to='agency_app.activity'),
        ),
    ]
