# Generated by Django 5.1.4 on 2025-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide_needed',
            field=models.BooleanField(default=False),
        ),
    ]
