# Generated by Django 5.1.4 on 2025-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_guide_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_guide',
            field=models.BooleanField(default=False),
        ),
    ]
