# Generated by Django 4.2.18 on 2025-04-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='assigned_guide',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guide_needed',
        ),
    ]
