# Generated by Django 4.2.18 on 2025-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
