# Generated by Django 4.2.18 on 2025-04-21 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planning', '0003_remove_itinerary_activity_itinerary_activity'),
        ('booking', '0008_booking_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_planning.trip'),
        ),
    ]
