# Generated by Django 4.2.18 on 2025-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0003_activity_travel_id'),
        ('trip_planning', '0002_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='activity',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='activity',
            field=models.ManyToManyField(to='agency_app.activity'),
        ),
    ]
