# Generated by Django 4.2.18 on 2025-04-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planning', '0003_remove_itinerary_activity_itinerary_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
